[package]
name = "rusty_state"
version = "0.1.0"
authors = ["cemoktra <bazz-dee@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
